name: Build and Deploy

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: loongstudio/docs
          TARGET_BRANCH: gh-pages
          BUILD_SCRIPT: yarn && yarn run build
          BUILD_DIR: docs/.vuepress/dist

  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror the Github organization repos to Gitee.
        uses: Yikun/hub-mirror-action@master
        with:
          src: 'github/loongstudio'
          dst: 'gitee/loongstudio'
          dst_key: ${{ secrets.ACCESS_TOKEN }}
          dst_token:  ${{ secrets.GITEE_ACCESS_TOKEN }}
          static_list: "docs"
          force_update: true
          debug: true